name: Crete Release on Push

on:
  push:
    branches: [ "main" ]
    paths:
      - terraform/**
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Create Release
        id: create_release
        uses: comnoco/create-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.semver.outputs.next }}
          release_name: ${{ steps.semver.outputs.next }}
          body: Changelog Contents
