name: Terraform Destroy
on:
 workflow_dispatch:

jobs:
 tf-destroy:
   runs-on: ubuntu-latest
   permissions: read-all
   env:
    LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
   steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Terraform                                                                      
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: | 
            terraform init -backend-config="access_key=${{ secrets.LINODE_ACCESS_KEY }}" -backend-config="secret_key=${{ secrets.LINODE_SECRET_KEY }}" -backend-config=bucket="${{ secrets.LINODE_BUCKET }}" 
        
      - name: Show Destroy plan
        run: terraform plan -destroy
        continue-on-error: true

      - name: Terraform destroy
        id: destroy
        run: terraform destroy -auto-approve
